apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-v1-0-0
  labels:
    app: service-v1-0-0
    applicationId: app_4eea145f-a415-42b3-b547-c799bf9f1d7b
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_0309f1f1-c4c6-469b-a720-eb309d881539
    environmentId: env_164c3963-b5dc-422d-84da-308498633ea9
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: service-v1-0-0
  template:
    metadata:
      labels:
        app: service-v1-0-0
        applicationId: app_4eea145f-a415-42b3-b547-c799bf9f1d7b
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_0309f1f1-c4c6-469b-a720-eb309d881539
        environmentId: env_164c3963-b5dc-422d-84da-308498633ea9
