apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-v1-0-0
  labels:
    app: app2-v1-0-0
    applicationId: app_9a3a6736-3292-4286-b1f4-abc088b35666
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_9b2e36b1-b844-4e28-837b-bc6f1a1e5402
    environmentId: env_440a0a07-1240-41b3-8d13-d7cca41760ac
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: app2-v1-0-0
  template:
    metadata:
      labels:
        app: app2-v1-0-0
        applicationId: app_9a3a6736-3292-4286-b1f4-abc088b35666
        version: v1.0.0
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_9b2e36b1-b844-4e28-837b-bc6f1a1e5402
        environmentId: env_440a0a07-1240-41b3-8d13-d7cca41760ac
